namespace PayloadLogging.Common.Models.PayloadLogging
{
  public class PayloadModel
  {
    /// <summary>
    /// Full source url of the request/response
    /// </summary>
    /// <value>Name of client application submitting the payload</value>
    public string Source { get; set; }

    /// <summary>
    /// Full payload received or generated by the client application
    /// </summary>
    /// <value>Full payload received or generated by the client application</value>
    public string Payload { get; set; }

    /// <summary>
    /// Type of Payload
    /// </summary>
    public string Type { get; set; }

    /// <summary>
    /// Correlation Id
    /// </summary>
    public string CorrelationId { get; set; }

    /// <summary>
    /// When available response code generated by the client application
    /// </summary>
    /// <value>When available response code generated by the client application</value>
    public int? ResponseCode { get; set; }
  }
}
